### ISSUE TITLE
Installing PYNQ first and then other steps error

### ISSUE THREAD

**Issue by krishnaadithya** [Xilinx/Kria-PYNQ#10]
dpkg: error processing archive /var/cache/apt/archives/vitis-ai-runtime_1.3.2-0
ubuntu5~20.04.2_arm64.deb (--unpack):
 trying to overwrite '/usr/bin/dump_op_weights', which is also in package libva
rt 1.4.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package vitis-ai-library.
Preparing to unpack .../vitis-ai-library_1.3.2-0ubuntu5~20.04.2_arm64.deb ...
Unpacking vitis-ai-library (1.3.2-0ubuntu5~20.04.2) ...
dpkg: error processing archive /var/cache/apt/archives/vitis-ai-library_1.3.2-0
ubuntu5~20.04.2_arm64.deb (--unpack):
 trying to overwrite '/usr/lib/libvart-runner-assistant.so', which is also in p
ackage libvart 1.4.0
Errors were encountered while processing:
 /var/cache/apt/archives/vitis-ai-runtime_1.3.2-0ubuntu5~20.04.2_arm64.deb
 /var/cache/apt/archives/vitis-ai-library_1.3.2-0ubuntu5~20.04.2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by skalade** [comment]
Hi there,

You're likely seeing this because the vitis-ai-runtime library versions don't match between what sysinit is trying to install (VART 1.3.2) and what we ship with Kria-PYNQ which is version 1.4.0. If you look at the install script we actually purge the previously installed libraries [here](https://github.com/Xilinx/Kria-PYNQ/blob/main/install.sh#L153). You should be able to resolve your issue by running
```
sudo apt remove --purge vitis-ai-runtime
```
Note that dpu-pynq overlays might not work with the older version of vitis-ai-runtime.

Thanks
Shawn

**Comment by krishnaadithya** [comment]
@skalade 

So they cannot be downloaded together?

**Comment by skalade** [comment]
Normally, if you installed Kria-PYNQ after the sysinit and accelerated apps, both should work, because the Vitis AI versions are close enough. If you follow my suggestion, the dpu-pynq examples might still work, but this has not been tested.
